on:
  workflow_call:
    inputs:
      date: 
        description: 'date'
        required: true
        default: NA
        type: string

jobs:
  echo_job:
    runs-on: ubuntu-latest
    outputs:
       test: ${{ steps.Result.outputs.result }}
    steps:
      - name: Echo Reusable Message
        run: |
            echo "Hello, ${{ inputs.date }}!"  >> $GITHUB_STEP_SUMMARY
            echo "1" >> $GITHUB_OUTPUT
      - name: Echo Result
        id: Result
        run: |
            echo  "result=1" >> $GITHUB_OUTPUT
